---
title: "Plots"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message = FALSE}
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
```


## Load in data 

```{r}
data("ny_noaa")
```


## Filtering data

```{r warning=FALSE}
set.seed(1)
sample_data =
ny_noaa %>% 
  mutate(
    tmax = as.numeric(tmax),
    tmin = as.numeric(tmin),
    id = as.factor(id),
    tmax = tmax / 10,
    tmin = tmin / 10,
    id = recode(id,`USC00308625` = "Tully_NY")
  ) %>% 
  
  filter(id %in% c("Tully_NY")) %>%     
  separate(date, into = c("year", "month","day"), sep = "-") %>% 
  na.omit() %>% 
  select(-month,-day) %>% 
sample_n(2000)
```


## Scatter plots 

### Association between tmin and tmax for each year in Tully. 

```{r warning=FALSE}
scatter_plots =
sample_data %>% 
  plot_ly(x = ~ tmin, y = ~ tmax, type = "scatter", mode = "markers",color = ~year, alpha = 0.5) 

scatter_plots
```

## Box plot

### Distribution of minimum temperature for each day in each year. 
```{r warning=FALSE}
boxplot = 
sample_data  %>%
  mutate(year = fct_reorder(year, tmin)) %>% 
  plot_ly(x = ~year, y = ~tmin, color = ~year, type = "box",
          colors = "Set2")
boxplot
```

## Bar plot 
### The number of days without snow in each year. 

```{r warning=FALSE}
bar_plot = 
  sample_data %>% 
  filter(snwd != "0") %>% 
  mutate(
    snwd = as.factor(snwd)
  ) %>% 
    count(snwd) %>% 
  mutate(snwd = fct_reorder(snwd,n)) %>% 
  plot_ly(x = ~snwd, y = ~n, type = ~ "bar", color = ~snwd)
bar_plot
```













